//! Known-answer + sign/recover cross-check for the multisig INNER roster-signature
//! digests (user-bound + legacy schemes).
//!
//! Two angles:
//!
//! 1. `inner_digests_match_chain` — reproduce the chain crate's inner digests
//!    byte-for-byte (chain id 114514 / `"Testnet"`). A drift in the type string,
//!    the `user` word, the raw-blob hashing, or the `0x1901 || domain || struct`
//!    envelope would change these. A mismatch = the node REJECTS the roster
//!    signature.
//!
//! 2. `sign_multisig_inner_round_trips` — a roster member signs each scheme and
//!    the signer recovers to that member's address via the same secp256k1
//!    primitive the node runs.
//!
//! Fixtures generated by executing the chain itself at the release
//! pin: chain id 114514, `user = 0x2222..22`, inner blob =
//! `{"type":"noop","params":{}}`, nonce = 1_735_689_600_000.

use metaflux_client::wallet::{
    Address, MultisigInnerScheme, Wallet, multi_sig_inner_digest, multi_sig_inner_digest_legacy,
    sign_multisig_inner, sign_recover_for_test_only,
};

const CHAIN_ID: u64 = 114514;
const NONCE: u64 = 1_735_689_600_000;
const BLOB: &[u8] = br#"{"type":"noop","params":{}}"#;

fn user() -> Address {
    Address::from_bytes([0x22; 20])
}

/// (1) Both inner digests reproduce the chain fixtures byte-for-byte.
#[test]
fn inner_digests_match_chain() {
    // Fixture M.legacy_inner_digest — MetaFluxAction over the raw blob bytes.
    assert_eq!(
        hex::encode(multi_sig_inner_digest_legacy(CHAIN_ID, BLOB, NONCE)),
        "439f9476f5235ef8637cd837382df24fc2dcb0b33261830e11e1467ed6600433",
        "legacy inner digest drift vs chain"
    );

    // Fixture M.userbound_inner_digest — MetaFluxMultiSigInner binding `user`.
    assert_eq!(
        hex::encode(multi_sig_inner_digest(CHAIN_ID, user(), BLOB, NONCE)),
        "b2fbf42acd0f24909cf7c3905d4a1b8503806b2f42c8bec22d9caacd70531e82",
        "user-bound inner digest drift vs chain"
    );

    // The two schemes MUST differ — binding `user` changes the digest, which is
    // the whole point of the user-bound scheme (cross-account replay defense).
    assert_ne!(
        multi_sig_inner_digest(CHAIN_ID, user(), BLOB, NONCE),
        multi_sig_inner_digest_legacy(CHAIN_ID, BLOB, NONCE),
        "user-bound and legacy inner digests must differ"
    );
}

/// (2) A roster member signs each scheme and the signature recovers that member.
#[test]
fn sign_multisig_inner_round_trips() {
    let wallet = Wallet::from_bytes([0x42; 32]).expect("wallet");

    for scheme in [MultisigInnerScheme::UserBound, MultisigInnerScheme::Legacy] {
        let digest = match scheme {
            MultisigInnerScheme::UserBound => multi_sig_inner_digest(CHAIN_ID, user(), BLOB, NONCE),
            MultisigInnerScheme::Legacy => multi_sig_inner_digest_legacy(CHAIN_ID, BLOB, NONCE),
        };
        let sig = sign_multisig_inner(&wallet, scheme, CHAIN_ID, user(), BLOB, NONCE)
            .expect("sign inner");
        assert!(sig.v == 27 || sig.v == 28, "legacy v for {scheme:?}");
        let recovered = sign_recover_for_test_only(&digest, &sig).expect("recover");
        assert_eq!(
            recovered,
            wallet.address(),
            "roster signature must recover the signing member ({scheme:?})"
        );
    }
}
